<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="css/normalize.css">
	<link rel="stylesheet" href="css/nav.css">
	<link rel="stylesheet" href="sss/sss.css">
	<link rel="stylesheet" href="css/character_page.css">
	<link rel="stylesheet" href="css/signup_page.css">	
	<link href="https://fonts.googleapis.com/css?family=Muli|Nunito" rel="stylesheet">
</head>